### ISSUE TITLE
Set up GitHub Actions

### ISSUE THREAD

**Issue by szepeviktor** [jdkato/txtlint#368]
Hello @jdkato! 👋 
Would you welcome a PR that sets up CI to do its job? Release on tags, test on each commit?

**Comment by nschonni** [comment]
There is https://github.com/errata-ai/vale/blob/v2/.github/workflows/main.yml, but also https://github.com/errata-ai/vale/blob/v2/.gitlab-ci.yml and https://github.com/errata-ai/vale/blob/v2/appveyor.yml which could be simplified

**Comment by szepeviktor** [comment]
- `.github/workflows/main.yml`˙run on every commit but does nothing unless it is a tagged release
- there is no per commit testing here on GitHub
- `.gitlab-ci.yml` Where is it running?

**Comment by nschonni** [comment]
I saw the link in the green checkmark on the last commit https://github.com/errata-ai/vale/commit/bd2b3287c77979e2826b895b7c0bae9ac21dd0e0

**Comment by szepeviktor** [comment]
Is there a mirror on GitLab?? 😲

**Comment by szepeviktor** [comment]
Okay. My offer is to move that testing here to GitHub.

**Comment by jdkato** [comment]
- `.github/workflows/main.yml` creates and uploads the assets provided with each [release](https://github.com/errata-ai/vale/releases). (It also used to run Vale's own [action](https://github.com/errata-ai/vale-action), which is where the on `pull_request` / `push` came from)
- `.gitlab-ci.yml` runs Vale's test suite on a Linux VM.
- `appveyor.yml` runs Vale's test suite on a Windows VM. 

I don't think there's a pressing need to change this.
