### ISSUE TITLE
TokenIgnores are not registered

### ISSUE THREAD

**Issue by MLNW** [jdkato/txtlint#398]
I am trying to ignore issues in FIGNOS figure definitions. Something like this: `{#fig:a-b-c-d-e}`

Though, adding *any* `TokenIgnores` directives to my ` .vale.ini` file does not get picked up when using `vale ls-config`:

`.vale.ini`

```
TokenIgnores = (#\+.+$)
#TokenIgnores = (\$+[^\n$]+\$+)
#TokenIgnores = (\*\*\{\w*\}\*\*)
#TokenIgnores = (?s) *{.*fig.*}
```

`vale ls-config`

```
{
...
  "TokenIgnores": {},
...
}

```

- OS CENTOS8/WSL2
- Install method: direct download
- Vale version: 2.14.0

**Comment by jdkato** [comment]
Where in your configuration file are you adding them? They should be under a file type section like `[*.md]`.

**Comment by MLNW** [comment]
You are right, that must be the issue. I remember I had them outside of my `[*.md]` block.
