### ISSUE TITLE
Unable to ignore URL in YAML with TokenIgnores

### ISSUE THREAD

**Issue by rachelrice** [jdkato/txtlint#402]
With macOS, Vale installed via Homebrew, Vale version 2.14.0

With `.vale.ini`:
```
StylesPath = styles
MinAlertLevel = suggestion

[*.yaml]
BasedOnStyles = spelling
TokenIgnores = (http[^\n]+)
```

With `styles/spelling/spelling.yml`:
```
extends: spelling
message: "Did you really mean '%s'?"
level: error
```

And `file.yaml`:
```
references:
  - https://docs.aws.amazon.com/workspaces/latest/adminguide/data-protection.html
```

When running `vale file.yaml`:
```
 file.yaml
 2:5   error  Did you really mean 'https'?    spelling.spelling
 2:51  error  Did you really mean             spelling.spelling
              'adminguide'?
 2:78  error  Did you really mean 'html'?     spelling.spelling
 ```
 
 Expected that `TokenIgnores = (http[^\n]+)` would result in 0 errors as the URL would be ignored.

**Comment by jdkato** [comment]
`TokenIgnores` and `BlockIgnores` only work for supported [markup formats](https://docs.errata.ai/vale/scoping#formats).

#383 discusses a few options for YAML (and other serialization formats).

**Comment by rachelrice** [comment]
> `TokenIgnores` and `BlockIgnores` only work for supported [markup formats](https://docs.errata.ai/vale/scoping#formats).
> 
> #383 discusses a few options for YAML (and other serialization formats).

Thanks @jdkato
