### ISSUE TITLE
Headings: Looking to add a style

### ISSUE THREAD

**Issue by dallasspohn** [jdkato/txtlint#404]
The standard for all Red Hat technical documentation is title case for all headings and titles. Diagram labels, table headings, procedure, and formal paragraph titles all fall under this heading, and consequently, standard title case capitalization rules apply. The currently accepted reference for determining title case is at https://titlecase.com/titlecase
We use sentence case for captions, legends, diagram labels, and table column headers. They are not classified as titles.

We write in asciidoc. How can I write a style (general instructions) to accommodate all these parameters?

- Linux - RHEL

Thanks!

**Comment by jdkato** [comment]
You'll want to use the [`capitalization`](https://docs.errata.ai/vale/styles#capitalization) extension point and then write rules that target specific [scopes](https://docs.errata.ai/vale/scoping#markup). 

You can currently only do this for the AsciiDoc equivalent of `<h{1,...}>` and `th` tags, though.
