### ISSUE TITLE
Markdown wiki links support

### ISSUE THREAD

**Issue by alefteris** [jdkato/txtlint#405]
Does Vale support wiki links in Markdown or is there a way to configure Vale to at least ignore them?

Wiki links have syntax that looks like:

```
[[wiki link]]
[[labelled|wiki link]]
```

Some tools like [Dendron](https://wiki.dendron.so/notes/3472226a-ff3c-432d-bf5d-10926f39f6c2/#wiki-links) and [Obsidian](https://help.obsidian.md/How+to/Internal+link) use this type of syntax.

Using Vale version 2.15.0

Thanks

**Comment by jdkato** [comment]
You can write a [`TokenIgnores`](https://docs.errata.ai/vale/scoping#non-standard-markup) pattern -- something like the following should work.

```ini
StylesPath = styles

[*.md]
BasedOnStyles = Vale

TokenIgnores = (\[\[.+\]\])
```
