### ISSUE TITLE
mac centricinstall instructions given for linux.

### ISSUE THREAD

**Issue by whytewolf** [jdkato/txtlint#406]
- OS Centos 8 stream

install directions are VERY mac os centeric I am not going install homebrew on my centos 8 system and the "script" and GitHub version are trying to use shasum which in linux is split into sha<bit>sum . causing failures.

**Comment by jdkato** [comment]
> I am not going install homebrew on my centos 8 system

OK.

Feel free to submit a PR with instructions for another method.
