### ISSUE TITLE
TokenIgnores not picking up errors in different lines

### ISSUE THREAD

**Issue by ramyaparimi** [jdkato/txtlint#409]
- OS (e.g., macOS, Windows, Linux, etc.) Mac
- Install method (e.g., Go, Homebrew, direct download, etc.) Homebrew
- Vale version (the result of `vale -v`) 2.14.0

I have a regex in TokenIgnores to ignore contents in markdown bold. Example: `**term**`. But terms in bold are still picked up as errors. Is there something I am missing to provide for TokenIgnores to not lint terms i bold?  Here is my .vale.ini

```
StylesPath = vale-styles

# suggestion, warning or error
MinAlertLevel = warning 

Vocab = GitHub

[*.md]
BasedOnStyles = Vale, GitHub

TokenIgnores = {%.*?%}, \ 
               {{.*?}}, \  
               (.|\/|-)?github(\/|-)?, \
               \(\/.*?\), \
               (\`{1}((.|\n)*?)\`{1}), \
               (\*{1}((.|\n)*?)\*{1}), \
               (\*{2}((.|\n)*?)\*{2}), \
               \[([^\[]+)\](\(.*\))

; \(\/.*?\), \  url in Markdown link, ex: (/rel/path/foo/bar)
; \[([^\[]+)\](\(.*\)) Link name and url in markdown ex : [link](url)
; {%.*?%}, \  liquid tag
; {{.*?}}, \    liquid object
; (.|\/|-)?github(\/|-)?  github in a relative path
; (\`{1}((.|\n)*?)\`{1}) backticks ex: `term`
; (\`{3}((.|\n)*?)\`{3}) codeblock
; (?s) *\_{1}((.|\n)*?)\_{1}, \ ignore file format _file_
; \*\*(.*)\*\*/ terms in bold
; vale --output=line --glob='!content/github/site-policy*.md' content > vale/vale-errors.txt 
; vale --glob='!content/github/site-policy*.md' content 
```

This the error:

<img width="835" alt="image" src="https://user-images.githubusercontent.com/33761166/154303608-587ff84f-a9d1-4650-bfba-3c4c61f50445.png">

**Comment by jdkato** [comment]
I feel like we've had this discussion a few times already, and my [comment here](https://github.com/errata-ai/vale/issues/387#issuecomment-993794303) still applies.

Your configuration, as written, isn’t going to work. 

I would start by removing all `TokenIgnores` entries for non-Liquid syntax.

**Comment by ramyaparimi** [comment]
Thanks so much for getting back. I apologize for repeatedly asking the same question. I will try deleting all the non liquid `ToeknIgnores` and trying it out once more.

**Comment by ramyaparimi** [comment]
Thanks so much for your suggestions. I removed all non liquid regex from my vale config.

```
StylesPath = vale

# suggestion, warning or error
MinAlertLevel = warning

Vocab = Docs

[*.md]
BasedOnStyles = Vale,Vocab

TokenIgnores = {%.*?%}, \ 
               {{.*?}}
```

Could you please let me know what I can do if terms from markdown links are picked up as error:

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/33761166/155363403-76a4274d-b6c5-483a-8ec4-df59fb9343fc.png">

**Comment by jdkato** [comment]
Could you provide the contents of (or a link to) the file?

**Comment by ramyaparimi** [comment]
Sorry for forgetting to include earlier. It is L21 in this link:

https://github.com/github/docs/edit/main/content/account-and-profile/setting-up-and-managing-your-github-user-account/managing-user-account-settings/integrating-jira-with-your-personal-projects.md

**Comment by jdkato** [comment]
I can't reproduce the issue (although it looks like the file has changed since your screenshot):

![Screen Shot 2022-02-23 at 10 18 20 AM](https://user-images.githubusercontent.com/8785025/155382380-716a2a07-0f2d-4749-aa86-c3dfa3caec2a.png)

Both standard Markdown links and image URLs should be ignored by default. If they aren't, it's usually due to there being either non-standard syntax in the file (such as Liquid tags) or a misbehaving `BlockIgnores` / `TokenIgnores` pattern.

**Comment by ramyaparimi** [comment]
Thanks so much for looking into it. I noticed that when syntax/spacing isn't followed properly, Vale is picking up terms from code blocks. For example, when a new line character is added between liquid tag and code block as per , Vale isn't picking up terms from code block. I wonder if it something similar with Vale picking up from markdown links. 
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/33761166/155735624-ccb90d30-572a-412d-b8c9-2cf2820df4b9.png">

I will post here if I find something related to that.
Thanks so much for your time and help 💖
