### ISSUE TITLE
Incorrect error placing in AsciiDoc when comments with the same error are present.

### ISSUE THREAD

**Issue by someth2say** [jdkato/txtlint#414]
Vale version: 2.15.2

Vale correctly skips errors in comments.
But, when the same error appears in a comment, and then in the content after the comment, then Vale incorrectly reports the error in the comment instead of the error in the content.

The following GIF explains the issue better than words:

![Peek 2022-03-03 08-52](https://user-images.githubusercontent.com/13310156/156522330-1a540b78-af96-46a4-8a75-c607cc079083.gif)

**Comment by jdkato** [comment]
This should be fixed in the next release.
