### ISSUE TITLE
Ignore metadata tags like title in HTML

### ISSUE THREAD

**Issue by kKronstainBrown** [jdkato/txtlint#415]
Is it possible to add to the ignored scopes list individual tags that would be in HTML head metadata? In particular, `title`. Our markdown to HTML transforms auto-generate titles with the contents of H1, but strip out all formatting. So things we have set to be ignored, like code phrases, aren't being ignored properly with the code ticks missing. I would just like to ignore all titles to get around the behavior.

**Comment by jdkato** [comment]
I'm not sure that I understand, are you running Vale on your Markdown or HTML?

**Comment by kKronstainBrown** [comment]
HTML.

**Comment by jdkato** [comment]
You can use [`SkippedScopes`](https://docs.errata.ai/vale/config#skippedscopes):

```ini
# By default, `script`, `style`, `pre`, and `figure` are ignored.
SkippedScopes = script, style, pre, figure, title
```
