### ISSUE TITLE
Questions: How does Vale comparable to TextLint in Pugins?

### ISSUE THREAD

**Issue by BradKML** [jdkato/txtlint#417]
Currently observing https://github.com/textlint/textlint/wiki/Collection-of-textlint-rule#rules-english and it seem to have a bit less of everything.

**Comment by jdkato** [comment]
I think this is a question that you’ll need to answer yourself: try both, use the one that fits your needs/preferences best.

**Comment by ChrisChinchilla** [comment]
@BrandonKMLee So…

Text lint takes a JavaScript approach, so every type of test you want to install is another NPM package, and thanks to the ways NPM packages work, this could mean lots and lots of dependencies and lots of different config files.

Vale is one Go binary, then a lot of YAML file to represent different rules and general configuration, and that's about it. So it's a lot leaner and more "centralised".

At least that's my perspective from my evaluations a few years ago that led me to Vale.
