### ISSUE TITLE
Exclude empty files from the metrics check

### ISSUE THREAD

**Issue by CollierCZ** [jdkato/txtlint#419]
I'd like to start using the `metrics` endpoint. We have some Markdown files in a directory that only have frontmatter in them. When running with simple metrics (like `words/sentences`), this results in a `NaN` error, which breaks the Vale run.

It would be possible to set up a script to exclude such files, but it would make the workflow a lot more complicated.

It'd be great if the `metrics` check could ignore such cases.

(Using Vale 2.15.3 on Linux installed with Homebrew)

**Comment by jdkato** [comment]
Yes, this will be fixed in the next release.
