### ISSUE TITLE
Spelling check incorrectly triggers in AsciiDoc with mixed markup

### ISSUE THREAD

**Issue by daobrien** [jdkato/txtlint#421]
- OS Linux
- Install method: direct download
- Vale version:  2.15.3

I'm just getting going using the spelling checker on our AsciiDoc files and have hit the following issue:
~~~
`admin:__clusterset_name__` fails on "clusterset". (That is, it's flagged as a typo instead of being skipped.)
`admin:_clusterset_name_` Ditto
`admin_clusterset_name` ditto.
 `_clusterset_` ditto.
~~~

The following variations are correctly skipped:
~~~
This is a sentence that includes `clusterset` and it is ok.
This includes `clusterset_`. OK
This uses `_clusterset`. OK
And this one uses `clusterset:admin`. OK
~~~

The term "clusterset" is not in the dictionary or allowlist (and shouldn't be). We currently convert AsciiDoc to DocBook XML for publishing, which is why we have this complex markup. This "double markup" should never be spell-checked, but we *do* need to spell-check `_emphasis_` terms (underscores only).

Is this a bug or am I missing something? I've been playing around with TokenIgnores but have yet to find a solution.

**Comment by jdkato** [comment]
This should be fixed in the latest release.
