### ISSUE TITLE
Doc: styles folder in this repo vs. https://github.com/errata-ai/styles

### ISSUE THREAD

**Issue by thernstig** [jdkato/txtlint#425]
The documentation is not very clear on this in the README.md. It's possible  it could need a doc improvement for newcomers to better understand.

In the README.md it has a link to https://github.com/errata-ai/styles which is said to contain all official styles.

At the same time, in this library the directory https://github.com/errata-ai/vale/tree/v2/styles exists with several styles.

Is https://github.com/errata-ai/vale/tree/v2/styles not officially supported then even though it exists in this repo? I am unsure how to grok this.

**Comment by jdkato** [comment]
As the README states, https://github.com/errata-ai/styles is the place to find styles ready for use.

You’ll also note that the `v2/styles` directory contains its own README that states:

> NOTE: These styles are maintained for testing purposes only. You can find the publicly available styles at https://github.com/errata-ai/styles.

**Comment by thernstig** [comment]
@jdkato got it, thanks. To make it more clear maybe place them in a tests/styles directory for users to know? The README is easy to miss. Just an idea 😄
