### ISSUE TITLE
Allow for comments in vocab accept/reject txt files

### ISSUE THREAD

**Issue by rainecheck** [jdkato/txtlint#437]
The current formatting of the `accept.txt` and `reject.txt` do not easily allow for comments linking to sources as to the context of why the line exists. I haven't found any historic issues that detail if this is an intentional design choice, a limitation, or just something that hasn't been considered.

**Comment by jdkato** [comment]
I think this is something that I'm unlikely to get around to looking at.

**Comment by jdkato** [comment]
This is actually going to be supported in the next release: any line starting with `# + space` will be considered a comment.
