### ISSUE TITLE
Can't sync on Windows

### ISSUE THREAD

**Issue by cranberry-clockworks** [jdkato/txtlint#441]
# System Information
__OS__: MS Windows 11. Version 21H2 (OS Build 22000.675)
__Install method__: `$ choco install vale`
__Vale version__: 
```Shell
$ vale --version
vale version 2.17.0
```
# Issue description
First, I created `ini` file in one of the `%APPDATA%` subfolder.
The content is `vale.ini` below:
```ini
StylePath = vale/styles
MinAlerLevel = suggestion

Packages = Microsoft

[*]
BasedOnStyles = Vale, Microsoft
```

Then I tried to execute `sync` command and got the error as follows:
```
PS C:\Users\Knight\Desktop> vale sync --config="C:\Users\Knight\AppData\Local\nvim\vale.ini"
mkdir : The system cannot find the path specified.
```

**Comment by jdkato** [comment]
You have a typo in your config: `StylePath` -> `StylesPath`.

**Comment by cranberry-clockworks** [comment]
Thanks a lot, my bad! It works!
