### ISSUE TITLE
Vale ignores laravel blade files

### ISSUE THREAD

**Issue by rottndandie** [jdkato/txtlint#447]
Hi!

I'm using Laravel for my php app, and I have some help files I want to run Vale against. It's not finding the files, and so it's not testing them. Here's my dir structure:

E:\xampp\htdocs\\.vale.ini
E:\xampp\htdocs\styles
E:\xampp\htdocs\project1
E:\xampp\htdocs\project1\resources\views\help\file1.blade.php

The blade.php files are basically HTML files with some php added via "Blade directives." But Vale ignores all of the .blade.php files as if they contain uncommented code.

In my .vale.ini, I added 

[formats]
blade.php = html

But that didn't make any difference. When I run
vale E:\xampp\htdocs\project1\resources\views\help\file1.blade.php
it returns with 0 errors, 0 warnings, and 0 suggestions, even though I purposely added text that should've been flagged.

What's the best way to convince Vale to examine my *.blade.php files as html?

Thanks!

**Comment by jdkato** [comment]
`blade.php` are not strictly valid HTML, so Vale can't lint them as such.

You can use `vale --ignore-syntax file1.blade.php`, but the results probably won't be great since this isn't a supported format.
