### ISSUE TITLE
Runtime error for the dita file

### ISSUE THREAD

**Issue by syeda-git** [jdkato/txtlint#452]
- OS = Window
- Install method =Chocolate 
- Vale version = 2.17

I am trying to run vale on a dita file. DITA-OT is on my system and i have defined the PATH to the bin directory of DITA-OT. The DITA-OT version is 3.7.
This is my vale.ini file

```
StylesPath = styles 
MinAlertLevel = suggestion  
Vocab = Base  
Packages = Microsoft, Readability  
[*.dita]  
BasedOnStyles = Vale, Microsoft, Readability
```

Getting this error:
![image](https://user-images.githubusercontent.com/44337085/175554182-1b2f5f46-d7a5-4803-887b-8818106c2b32.png)

Thanks...
Syed

**Comment by syeda-git** [comment]
@jdkato 
Curious if this defect is going to be fixed?

**Comment by jdkato** [comment]
This should be fixed in the next release.

**Comment by syeda-git** [comment]
@jdkato I am facing this issue again. Do i open another issue?
