### ISSUE TITLE
Spell checking plural abbreviations

### ISSUE THREAD

**Issue by CollierCZ** [jdkato/txtlint#464]
The most recent version of Vale corrects spell checking when there are words with mixed capitalization (like PHPStorm). This is definitely a positive change overall and led to finding some errors I wouldn't have otherwise.

Unfortunately, this makes us run into issues with things like abbreviations that can be pluralized. Example: data protection agreements (DPAs), where DPAs is seen as a spelling error. Anyway we could get around this without instituting our own spelling rule or adding all the abbreviations to an accept list?

**Comment by jdkato** [comment]
You can add a pattern to your accept list such as `[A-Z]{3,}s`.

**Comment by CollierCZ** [comment]
Ah, thank you, @jdkato!

**Comment by CollierCZ** [comment]
But testing that seems to accept things like `dhks`. It's no longer marked as an error.

**Comment by jdkato** [comment]
You're right, but this should work `(?-i)[A-Z]{3,}s`.

**Comment by CollierCZ** [comment]
Thanks so much!
