### ISSUE TITLE
Follow standard naming conventions for releases

### ISSUE THREAD

**Issue by seemiller** [jdkato/txtlint#465]
When creating releases for different operating systems and architectures, follow a standard naming convention.

A common pattern is to reference the OS, then the architecture. This makes it considerably easier to script downloads when using the following commands in a makefile or other script:
```shell
NAME=vale
HOST_OS=$(shell go env GOOS)
HOST_ARCH=$(shell go env GOARCH)
VERSION=v2.20.1
```

For example, consider a convention like this - `$NAME-$HOST_OS-$HOST_ARCH-$VERSION`
```shell
vale-darwin-amd64-v2.20.1.tar.gz
vale-darwin-arm64-v2.20.1.tar.gz
vale-linux-amd64-v2.20.1.tar.gz
vale-linux-arm64-v2.20.1.tar.gz
vale-windows-amd64-v2.20.1.zip
vale-windows-arm64-v2.20.1.zip
```

The names are currently like this:
```shell
vale_2.20.1_Linux_64-bit.tar.gz
vale_2.20.1_Linux_arm64.tar.gz
vale_2.20.1_macOS_64-bit.tar.gz
vale_2.20.1_macOS_arm64.tar.gz
vale_2.20.1_Windows_64-bit.zip
```

To script downloading these, you have to toggle between `64-bit` and `arm64` for the architecture on both Linux and Mac versions. And you have to convert `darwin` to `macOS`

**Comment by jdkato** [comment]
I think if I were to change this now, the impact of breaking existing scripts would be more significant than the perceived benefit for future scripts.
