### ISSUE TITLE
Vale v2.20.0 - Styles based on the Substitution endpoint can't recognize whitespace characters 

### ISSUE THREAD

**Issue by sarahlwelton** [jdkato/txtlint#471]
OS: Windows 10 
Install method: Chocolatey package management 
Vale version: 2.20.0 

When working with pre-defined or custom-written styles for the substitution extension point, Vale no longer recognizes "bad" phrases if they include a whitespace character. 

For example, in the pre-defined Contractions.yml from the Microsoft Style Guide implementation: 

![image](https://user-images.githubusercontent.com/110928505/184407387-36e408cb-c551-4fd8-9db8-b6889fd433a4.png)

![image](https://user-images.githubusercontent.com/110928505/184406718-e66ae437-f3b1-478f-9014-bc0e1a4c25e5.png)

Only `cannot` gets flagged as an error. Any phrase that includes a space doesn't register a flag. 

The text doesn't get flagged when running Vale from the command line, either.

**Comment by jdkato** [comment]
I'm not able to reproduce this:

![Screen Shot 2022-08-12 at 11 57 57 AM](https://user-images.githubusercontent.com/8785025/184425514-3316511f-d138-4ca9-a04c-c40eff1a0471.png)

What does your `.vale.ini` look like?

**Comment by sarahlwelton** [comment]
![image](https://user-images.githubusercontent.com/110928505/184426570-9a8a52c8-c810-4fb4-8ec4-df5461fc8fae.png)

I've been testing in a .txt file, though I'm not sure if that would really make a difference. It's such a weird problem to be having!

**Comment by jdkato** [comment]
I get the same (expected) results in a `.txt` file too. Can you try disabling your `Vocab` temporarily? (Remove the line or make it a comment.)

**Comment by sarahlwelton** [comment]
Oddly enough, it seems that the Vocab being turned off makes it work? 

![image](https://user-images.githubusercontent.com/110928505/184428581-d286a8b9-0356-4388-adcf-972c382379b0.png)

Should I remove the Vocab files and find a new way of implementing them? Just curious about where to go from here.

**Comment by jdkato** [comment]
My guess is that you have an entry that is unintentionally general in scope (likely something to do with spaces). Could you share the `accept.txt` file?

**Comment by sarahlwelton** [comment]
Yup, you were correct. Some unescaped periods. Sorry for wasting your time with a non-existent bug!
