### ISSUE TITLE
Passing asciidoctor document attributes does not work as descrbed

### ISSUE THREAD

**Issue by aireilly** [jdkato/txtlint#479]
https://vale.sh/docs/topics/scoping/#asciidoc describes being able to set document attributes but I can't get this to work. 

```cmd
$ vale -v
vale version 2.20.1
```
Sample asciidoc file:

```asciidoc
:_content-type: CONCEPT
[id="REPLACE_ME_WITH_ID_{context}"]
= Sample

ifdef::my-context[]
Get the UUID for the known cluster and/or the thing you want to add a worker node to from the list of managed clusters
endif::[]
```

sample `.vale.ini`:

```ini
StylesPath = .vale/styles

MinAlertLevel = suggestion

[formats]

[*.adoc]
BasedOnStyles = RedHat

[asciidoctor]
attribute = my-context
```

Vale does not apply the `my-context` attribute and does not lint inside the ifdef block

It would be cool if Vale could do something like the opposite of `BlockExcludes` (BlockIncludes?!) for this situation.

**Comment by themr0c** [comment]
https://vale.sh/docs/topics/scoping/#asciidoc

```
[asciidoctor]
attribute = value
```
I believe that in your example, you defined the `attribute` attribute with the `my-context` value. Therefore, the `my-context` attribute is left undefined.

**Comment by aireilly** [comment]
I misunderstood the docs. This works: 

```
[asciidoctor]
my-context = YES
```

**Comment by aireilly** [comment]
OK, I think we can close :) Thanks @themr0c
