### ISSUE TITLE
Vocabularies Don't Flag Errors for Phrases Containing Whitespace Characters

### ISSUE THREAD

**Issue by sarahlwelton** [jdkato/txtlint#483]
- OS - Windows 10
- Install method - Chocolatey Package Manager
- Vale version - 2.20

I've been driving myself nuts because I can't figure this out. 

I've gone and done a completely clean implementation of Vale - it only has the built in styles loaded and nothing else. 

But for some reason, if a phrase in the `accept.txt` contains a whitespace character, Vale won't detect it as an incorrect version of the phrase: 

![image](https://user-images.githubusercontent.com/110928505/187952718-e911ec70-8263-4e96-99e9-6ca485d9eee2.png)

![image](https://user-images.githubusercontent.com/110928505/187952843-abf19cfe-da7b-4861-adff-7c1c431c56c3.png)

![image](https://user-images.githubusercontent.com/110928505/187952936-fed5d4b8-6ce9-4da0-bf3a-5e223c300493.png)

So, `Word` gets picked up, but `this phrase` doesn't get flagged as an error. 

I started trying to make a `substitution` rule to combat this but it would be so much easier if this just... Worked. :(

**Comment by jdkato** [comment]
This works as you expect in the latest release (v2.20.1). It was just recently published to Chocolatey, though, so you probably need to update.
