### ISSUE TITLE
vale does not correctly capture regex with ending square bracket

### ISSUE THREAD

**Issue by cheungaryk** [jdkato/txtlint#485]
OS: macOS, v12.5.1 (Monterey) with M1 max chip
Install method: Homebrew
Vale version: 2.20.1

I am having trouble implementing a regex capture with sentences with square bracket at the end. I think it may be a bug based on some testing.

I am trying to capture empty or blank brackets (`[]`). Below is a screenshot from regexpal showing that the regex expression `[\w-_\.]+\[[\s]*\]` works:

![Screen Shot 2022-09-06 at 3 19 50 PM](https://user-images.githubusercontent.com/10934908/188750497-d921311b-6288-4bff-9931-e4759e4536ad.png)

This is what I have in my vale yaml file:

```yaml
extends: existence
message: "'%s' does not have an alt text."
ignorecase: true
level: error
raw:
  - '[\w-_\.]+\[[\s]*\]'
```

My text file:

```asciidoc
image::test-with-alt-text.png[alt text]
image::test-wo-alt-text.png[]
image::test-wo-blank-alt-text.jpg[ ]
```

But when I run vale against the file, I got no errors:

![Screen Shot 2022-09-06 at 3 22 02 PM](https://user-images.githubusercontent.com/10934908/188750752-c085de10-b239-443d-a24a-7fad04875191.png)

If I break the first sentence by removing the ending square bracket, I get the correct errors:

![Screen Shot 2022-09-06 at 3 22 45 PM](https://user-images.githubusercontent.com/10934908/188750870-e81ea1b5-3c71-4d1a-9f95-a21281875d39.png)

A couple more scenarios (no screenshots because they are self-explanatory):
- If I remove the first sentence altogether, expected errors but vale found no errors
- If I remove `\]` at the end of the regex expression and kept the first sentence, expected errors but vale found no errors

Did I do something wrong? Or is it a bug? Thank you!

**Comment by jdkato** [comment]
If you want to match against raw markup, you need to add [`scope: raw`](https://vale.sh/docs/topics/scoping/#markup) to your rule.
