### ISSUE TITLE
jdkato/vale Docker images are missing recent releases

### ISSUE THREAD

**Issue by ddbeck** [jdkato/txtlint#489]
On a project I work on, we use the [jdkato/vale](https://hub.docker.com/r/jdkato/vale/tags) Docker images. It's very handy, since Dependabot can automatically upgrade Dockerfiles to the latest version.

However, recent releases haven't been published to Docker Hub. It appears that none of the releases following v.2.18.0 have been released as Docker images. Is there any chance that these releases could resume there? Thank you!

**Comment by ChrisChinchilla** [comment]
I noticed this too a while ago, @jdkato I am happy to handle if you point me in the right direction. We could create a new action to handle it automatically.

**Comment by jdkato** [comment]
I'll get the latest version out today. @ChrisChinchilla, check out the [install](https://github.com/errata-ai/install) repo for the beginning of an Action to automate this.

**Comment by jdkato** [comment]
The latest is out now.

**Comment by carno** [comment]
Looks like https://hub.docker.com/r/jdkato/vale/tags stopped at `v2.22.0` - is that something planned and people should start their own images?
