### ISSUE TITLE
Docker Image for v2.20.2 not runnable

### ISSUE THREAD

**Issue by Taucher2003** [jdkato/txtlint#490]
The Docker image for version `v2.20.2` is not runnable, the previous version `v2.18.0` works fine.

![image](https://user-images.githubusercontent.com/39954661/190877078-29030eef-d0eb-4ed3-9b1f-e8d4ce13c347.png)

**Comment by jdkato** [comment]
This should be fixed now.

**Comment by Taucher2003** [comment]
I can confirm that it works now, thanks
