### ISSUE TITLE
Thesaurus rule support, feature request

### ISSUE THREAD

**Issue by Thorsten-Sick** [jdkato/txtlint#495]
Hi

It would be awesome to a thesaurus type rule. Depending on setting and an imported thesaurus (libre office, ...):

If a word listed in the thesaurus is used X times in a size Y text window a warning (and maybe a list of alternatives) is raised.

**Comment by jdkato** [comment]
The next release of Vale will enable Tengo's [`os`](https://github.com/d5/tengo/blob/master/docs/stdlib-os.md) module in `script` rules, so something like this will be possible.

**Comment by rohennes** [comment]
> The next release of Vale will enable Tengo's [`os`](https://github.com/d5/tengo/blob/master/docs/stdlib-os.md) module in `script` rules, so something like this will be possible.

Is Tengo's [`os`] module included in a Vale release yet? This is something we're looking for but I don't think it worked when I last tried it. Thanks!

**Comment by jdkato** [comment]
I never released this because it changes the security implications of downloading and using third-party styles pretty dramatically.
