### ISSUE TITLE
Enable checking for specific frontmatter

### ISSUE THREAD

**Issue by phxnsharp** [jdkato/txtlint#504]
We have a Hugo based documentation site with a lot of 'lists' that are defined mostly in the front matter. For example, a glossary entry might look like:

```markdown
---
title: RACI
acronym: Responsible, Accountable, Consulted, Informed
description: The RACI model describes participation by various roles in completing tasks or deliverables for a project or business process
more_info: https://en.wikipedia.org/wiki/Responsibility_assignment_matrix
---
```

Note that all of the content is in the front matter and the markdown is actually blank. It is rendered by Hugo templates. This gives us a lot of flexibility, for example we can read these files and export other formats. 

Even if we weren't doing that, having the ability to check titles, which appear to the user in menu and bread-crumb lists, would be of value. 

We have used Vale successfully in other contexts and like what it can do for us. Unfortunately Vale currently has a hardcoded regex to ignore the front matter. Worse, the code that implements the BlockIgnores configuration option is in the same function with the hardcoded removal of the front-matter. If we turn off the 'code' scope, BlockIgnores no longer work and we can no longer customize the linting. 

Vale 2.20.2 installed by downloading package from GitHub into a GitHub codespace.

**Comment by jdkato** [comment]
Yes, this is intended behavior.

Front matter isn't Markdown and so features (such as `BlockIgnores`) that involve processing/understanding Markdown syntax won't work.

If you have a rule that you want to apply to front matter generally, you can use `scope: raw`. A better approach, though, might be to use a script to parse the front matter and only pass the desired keys (such as `title`) to Vale.

(Related to #117.)

**Comment by phxnsharp** [comment]
I had read all the previous issues related to front matter. However, I feel this would be a common desire and the tools are not good for solving it now. If you write a script to pull out content to be validated, the errors would then be disassociated from the original context (file and line number). It also would not be easy to integrate with editors like [VS Code](https://github.com/errata-ai/vale-vscode). Besides, this feels like a common desire (vale check of titles of pages), does everyone have to come up with their own scripts to do this? 

I understand that you may not have time or priority to implement it, but shouldn't it at least be an enhancement request that is left open instead of just closed as "will not implement"? The code is currently hardcoded in a way that explicitly prevents customization to fix this. Vale already has rich semantics for understanding code. It can pull out comment blocks. Being able to pull out specific YAML/frontmatter values doesn't feel that different.
