### ISSUE TITLE
Inconsistent behavior when ignoring front matter

### ISSUE THREAD

**Issue by phxnsharp** [jdkato/txtlint#506]
Hugo supports front matter in .html files just like in .md files. Vale ignores front matter in .md files but does not ignore front matter in .html files. This inconsistency makes it difficult to write scripts around vale (such as one trying to address #504).

vale version 2.20.2
Ubuntu 20.04.5 LTS

**Comment by jdkato** [comment]
See https://github.com/errata-ai/vale/issues/507#issuecomment-1297306579.
