### ISSUE TITLE
Extend Google style

### ISSUE THREAD

**Issue by c0rn1ie** [jdkato/txtlint#510]
- Linux
- AUR
- 2.20.1

The Google style includes Acronyms.yml with a list of exceptions: https://github.com/errata-ai/Google/blob/master/Google/Acronyms.yml#L10.

Is it possible to extend the list without editing `Acronyms.yml`?

**Comment by jdkato** [comment]
Yes, create a [Vocab](https://vale.sh/docs/topics/vocab/).
