### ISSUE TITLE
loadConfig infinite Loop

### ISSUE THREAD

**Issue by tpeacock19** [jdkato/txtlint#520]
The recent commit https://github.com/errata-ai/vale/commit/05cd546ce2e452d7751d1e3a86a23d835f7e145a introduced an un-terminated loop when using `--config` option _without_ having an existing `~/.vale.ini` file. When running vale on any file with the aforementioned conditions it simply hangs. The function `loadConfig` does not seem to reference any cli parameters.

**Comment by jdkato** [comment]
This should be fixed now.
