### ISSUE TITLE
E100 [.vale.ini not found] Runtime error

### ISSUE THREAD

**Issue by chmouel** [jdkato/txtlint#524]
```console
% vale --version
vale version 2.21.1
```

I keep getting :

```console
E100 [.vale.ini not found] Runtime error
````

since i have updated to latest release, while the .vale.ini is definitively in the path from where i run the command, which is this file available here https://github.com/openshift-pipelines/pipelines-as-code/blob/main/.vale.ini

**Comment by jdkato** [comment]
This should be fixed now.
