### ISSUE TITLE
vale 2.21.1 on macOS doesn't automatically detect .vale.ini, and must forceably be passed --config

### ISSUE THREAD

**Issue by rainecheck** [jdkato/txtlint#525]
Running on macOS 12.6.1 via brew, vale v2.21.1 (will update to 2.21.2 when brew gets it).

Vale does not detect `.vale.ini` at root level of project, when being run from command-line at said root level of project.
`vale .` <-- fails
`vale . --config='.vale.ini'` <-- succeeds

This replicates when in the working directory up or down 1 level from the `.vale.ini` file.

Assuming this is related to [#518](https://github.com/errata-ai/vale/issues/518).

**Comment by jdkato** [comment]
This should be fixed in the latest release.

Just to confirm, do you have a `.vale` directory in your `StylesPath`?

(#524)

**Comment by rainecheck** [comment]
Yes, we use `StylesPath = ./.vale/styles`.
Confirmed fixed with 2.21.2 binary.
