### ISSUE TITLE
Vale on/off comments do not work on formatted Markdown content

### ISSUE THREAD

**Issue by nicklem** [jdkato/txtlint#529]
- OS: macOS Ventura 13.0.1 (M2)
- Install method: Homebrew
- Vale version: 2.21.2

We're running into some errors when ignoring blocks of non-plain content in Markdown files, such as titles, lists, and paragraphs.

This may be related to https://github.com/errata-ai/vale/issues/340.

To reproduce:

- **This works** (ignores the unknown word): 

```
<!-- vale off -->
blarg
<!-- vale on -->
```

- **These don't** (they flag the unknown word):

```
<!-- vale off -->
### blarg
<!-- vale on -->
```

```
<!-- vale off -->
- blarg
<!-- vale on -->
```

```
<!-- vale off -->

blarg

<!-- vale on -->
```

Thanks for taking a look! 😄

**Comment by jdkato** [comment]
I can't reproduce this:

![Screenshot 2022-11-29 at 11 19 59 AM](https://user-images.githubusercontent.com/8785025/204626194-93d569be-3951-40ab-a5a0-faa072844a9a.png)

Is it possible for you to share one of the real files that you've observed this behavior?

It would also be helpful to see your `.vale.ini`.

**Comment by nicklem** [comment]
Thanks for your reply.
We did in fact notice and fix an issue on our side with our `.vale.ini`.
Everything works now. 👍
