### ISSUE TITLE
Vale spelling is flagging the word `metric's`

### ISSUE THREAD

**Issue by nickvigilante** [jdkato/txtlint#540]
vale version 2.21.3

We ran a file that contained `metric's` as the possessive form of the word metric, and Vale flagged that as erroneous. It's easy to work around, but it's weird that it did that in the first place.

**Comment by theletterf** [comment]
What is the rule for that detection? Could you paste it here?

**Comment by jdkato** [comment]
I've updated Vale's default [dictionary](https://github.com/errata-ai/vale/tree/v2/pkg/spell/data) to include this case.

It currently has 81530 words (+multiple variations of many), but some cases are going to be missed from time to time.
