### ISSUE TITLE
TokenIgnores Question

### ISSUE THREAD

**Issue by Tiberriver256** [jdkato/txtlint#546]
Hello,

I am trying to setup my ini file to ignore liquid syntax. (i.e., `{{ variable }}`, `{% if %} Content worth scanning with vale {% endif %}`)

I added the following TokenIgnores

```ini
# Exclude `{{ ... }}`, `{% ... %}`
TokenIgnores = ({{ .* }}.*?{{ ?/.* }}), ({% .+ %})
```

But I'm still getting:

![image](https://user-images.githubusercontent.com/6989492/211443305-b73f6002-ad7b-41c8-9d9b-513afef4e2f2.png)

My `vale ls-config`:

```json
{
  "BlockIgnores": {},
  "Checks": null,
  "Formats": {},
  "Asciidoctor": {},
  "FormatToLang": {},
  "GBaseStyles": [
    "Vale",
    "Google",
    "Readability"
  ],
  "GChecks": {},
  "IgnoredClasses": null,
  "IgnoredScopes": null,
  "MinAlertLevel": 0,
  "Vocab": [
    "MyVocab"
  ],
  "RuleToLevel": {},
  "SBaseStyles": {},
  "SChecks": {},
  "SkippedScopes": null,
  "Stylesheets": {},
  "StylesPath": "SomeFolderOnMyDrive/styles",
  "TokenIgnores": {
    "*": [
      "({{ .* }}.*?{{ ?/.* }})",
      "({% .+ %})"
    ]
  },
  "WordTemplate": "",
  "DictionaryPath": "",
  "NLPEndpoint": ""
}
```

**Comment by jdkato** [comment]
I'd suggest ignoring the `article` (or `ul`) element with either [`IgnoredClasses`](https://vale.sh/docs/topics/config/#ignoredclasses) or `SkippedScopes`.
