### ISSUE TITLE
Linting XML files

### ISSUE THREAD

**Issue by techauthoruk** [jdkato/txtlint#551]
Ubuntu 22.04 LTS in WSL2 (windows 10)
Vale 2.15.4

Is it possible to lint XML files using Vale? Stuff I have read says it should be supported, but when I first  attempted to lint a file I got an error saying xsltproc was missing. I installed that, but when I attempt to lint, I get this:

```bash
E100 [lintXML] Runtime error

no XSLT transform provided

```
Am I missing something (I tried to create an XLT file for the XML file, but this seems to make no difference), or will Vale not lint XML?

Can anyone assist? I'm totally clueless about XML, but I'm having to work with some content that is created in XML. Hope someone can enlighten me.

**Comment by jdkato** [comment]
Vale does support XML -- but you need instruct it on how to convert to HTML with an XSLT transform, as [shown here](https://vale.sh/docs/topics/scoping/#xml). Most projects, such as DocBook, should provide this.
