### ISSUE TITLE
Ignore rules or styles from CLI?

### ISSUE THREAD

**Issue by daobrien** [jdkato/txtlint#554]
- Fedora 36
- Installed from self-maintained RPM repo
- vale version 2.22.0

I couldn't find this in the docs, but I'd like to either skip or ignore certain rules or styles from the CLI. I don't want to disable the rule in the config because it's usually required, but it does happen when a rule or style needs to be ignored for a file set.

thanks

**Comment by jdkato** [comment]
Not currently possible.

Closing in favor of #466, which covers basically the same request.

**Comment by jdkato** [comment]
This is possible now in [`v2.23.0`](https://github.com/errata-ai/vale/releases/tag/v2.23.0).
