### ISSUE TITLE
Vale CLI: out of memory

### ISSUE THREAD

**Issue by bottom-feeder** [jdkato/txtlint#555]
Trying to lint a big HTML file (~4MB, ~30k strings) and get the following error: 

'runtime: VirtualAlloc of 4210688 bytes failed with errno=1455
fatal error: out of memory'

- OS: Windows
- Install method: chocolatey
- Vale version: 2.22.0
- System memory: 16 GB

Any way to work around this, except splitting the file?

**Comment by jdkato** [comment]
I imagine that this is due to Vale doing something unnecessarily inefficient since 4MB isn't that big. I'll look into it when I get a chance.

**Comment by universemaster** [comment]
Hi @bottom-feeder.  I have a [performance issue](https://github.com/errata-ai/vale/issues/567) too.  Can you try [2.15.4](https://github.com/errata-ai/vale/releases/tag/v2.15.4) and let us know if it helps?
